### ISSUE TITLE
Can't use getenv() directly on application.config.php

### ISSUE THREAD

**Issue by christopher-francisco** [abacaphiliac/zend-phpdotenv#7]
I'm guessing it's because the module is loaded after. I'm trying to enable cache based on env like this:

``` php
...
    'config_cache_enabled' => getenv('ENVIRONMENT') !== 'development',
    'module_map_cache_enabled' => getenv('ENVIRONMENT') !== 'development',
```

But it seems `getenv('ENVIRONMENT')` returns blank in here. Any ideas?

**Comment by abacaphiliac** [comment]
you're correct. in this case you may want to load your environment variable(s) in your index file instead.

the zendframework skeleton solves environment-based config caching another way, using a separate application config with development stack overrides. the index file will merge the override file if it is copied into place. the dist file is available in the repo, while the non-dist version is ignored.
https://github.com/zendframework/ZendSkeletonApplication/blob/master/public/index.php#L35
https://github.com/zendframework/ZendSkeletonApplication/blob/master/config/development.config.php.dist

i follow the zendframework skeleton approach in my zf2 applications. zf also provides a development-mode command which copies the development override file into place when enabled:
https://github.com/zendframework/ZendSkeletonApplication#development-mode

**Comment by christopher-francisco** [comment]
@abacaphiliac I understand, sounds reasonable. Is there a particular reason for this repo to load the dotenv as a Module using event manager?

**Comment by abacaphiliac** [comment]
i created it for 2 reasons:
1. i don't like changing the difficult-to-test application index file
2. i didn't want the env file to be loaded on every request

the latter caused an issue that has been requested: after env vars were injected into the cached config, subsequent requests obviously did not have access to the env vars.

**Comment by christopher-francisco** [comment]
@abacaphiliac Understood, pretty good reasons. I'll do as you suggest in your first comment. Thanks for the help!
